version: "3.9"
services:
  web:
    environment:
      - DATABASE_URL=${DATABASE_URL_PROD}
      - SECRET_JWT=${SECRET_JWT}
    depends_on:
      - db
    networks:
      - mynet
    image: alexfrunza/fiicode_backend_web
    build: .
    command: >
      sh -c "npx prisma generate && 
            npx prisma migrate deploy && 
            npm run ${ENV}"
    volumes:
      - ${LOCAL_IMAGES_FOLDER}:/app/images
    ports:
      - 80:3000

  db:
    image: postgres
    hostname: postgres
    networks:
      - mynet
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${DB_PORT}:5432

networks:
  mynet:
    driver: bridge
