version: "3.9"
services:
  web:
    environment:
      - DATABASE_URL=${DATABASE_URL_PROD}
      - SECRET_JWT=${SECRET_JWT}
      - API_KEY_MAILGUN=${API_KEY_MAILGUN} 
      - DOMAIN_MAILGUN=${DOMAIN_MAILGUN}
      - SENDER_MAILGUN=${SENDER_MAILGUN}
    depends_on:
      - db
    networks:
      - mynet
    image: alexfrunza/fiicode_backend_web
    build: .
    command: >
      sh -c "npx prisma generate && 
            npx prisma migrate deploy && 
            npm run ${ENV}"
    volumes:
      - ${LOCAL_ASSETS_FOLDER}/imagesIC:/app/assets/imagesIC
      - ${LOCAL_ASSETS_FOLDER}/imagesArticles:/app/assets/imagesArticles
      - ${LOCAL_ASSETS_FOLDER}/videosArticles:/app/assets/videosArticles
    ports:
      - 80:3000

  db:
    image: postgres
    hostname: postgres
    networks:
      - mynet
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${DB_PORT}:5432

networks:
  mynet:
    driver: bridge
